services:
  - type: web
    name: finance-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn finance_api.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: RENDER
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"