services:
  - type: web
    name: finance-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start_render.sh"
    envVars:
      - key: RENDER
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"