# Generated by Django 4.2.7 on 2025-10-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['usuario', 'leida', '-created_at'], name='notificatio_usuario_1635c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['usuario', '-created_at'], name='notificatio_usuario_ec8ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['usuario', 'tipo', 'leida'], name='notificatio_usuario_65d24c_idx'),
        ),
    ]
