# Generated by Django 4.2.7 on 2025-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['usuario', '-fecha'], name='transaction_usuario_b05419_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['usuario', 'fecha'], name='transaction_usuario_90fb86_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['usuario', 'categoria', 'fecha'], name='transaction_usuario_3219d4_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['fecha'], name='transaction_fecha_bf8221_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['usuario', '-fecha'], name='transaction_usuario_ccd307_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['usuario', 'fecha'], name='transaction_usuario_f54e55_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['fecha'], name='transaction_fecha_9b2031_idx'),
        ),
    ]
