# Generated by Django 4.2.7 on 2025-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savinggoal',
            index=models.Index(fields=['usuario', 'completada', '-created_at'], name='goals_savin_usuario_0728c3_idx'),
        ),
        migrations.AddIndex(
            model_name='savinggoal',
            index=models.Index(fields=['usuario', '-created_at'], name='goals_savin_usuario_d046ef_idx'),
        ),
        migrations.AddIndex(
            model_name='savinggoal',
            index=models.Index(fields=['usuario', 'fecha_limite'], name='goals_savin_usuario_c2ffea_idx'),
        ),
    ]
