# Generated by Django 4.2.7 on 2025-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', '-created_at'], name='loans_loan_user_id_777f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'date'], name='loans_loan_user_id_b315de_idx'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['loan', '-date'], name='loans_loanp_loan_id_3ece93_idx'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['date'], name='loans_loanp_date_51a6d7_idx'),
        ),
    ]
