# Generated by Django 4.2.7 on 2025-09-18 18:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categorybudget',
            name='unique_budget_category',
        ),
        migrations.RemoveConstraint(
            model_name='monthlybudget',
            name='unique_user_month_budget',
        ),
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together={('presupuesto_mensual', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlybudget',
            unique_together={('usuario', 'año', 'mes')},
        ),
    ]
