# Generated by Django 4.2.7 on 2025-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_remove_categorybudget_unique_budget_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['usuario', 'activa', '-created_at'], name='budgets_bud_usuario_8254d2_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['usuario', '-created_at'], name='budgets_bud_usuario_1a3885_idx'),
        ),
        migrations.AddIndex(
            model_name='categorybudget',
            index=models.Index(fields=['presupuesto_mensual', 'categoria'], name='budgets_cat_presupu_3c0019_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybudget',
            index=models.Index(fields=['usuario', '-año', '-mes'], name='budgets_mon_usuario_468f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybudget',
            index=models.Index(fields=['usuario', 'activo'], name='budgets_mon_usuario_1338d6_idx'),
        ),
    ]
